"""Alembic script file template."""

from alembic import op
import sqlalchemy as sa

revision = '6721010c96a7'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Drop check constraints that compare text to roles/languages to prevent cast issues
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check")
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_language_check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_atoms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('competency_id', sa.String(length=50), nullable=False),
    sa.Column('remediation_type', sa.Enum('AUDIO_VISUAL', 'SIMULATION', 'MIND_MAP', name='remediationtype'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_atoms_competency_id'), 'knowledge_atoms', ['competency_id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('grade_level', sa.String(length=50), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('competency_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='modulestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_competency_id'), 'modules', ['competency_id'], unique=False)
    op.create_index(op.f('ix_modules_grade_level'), 'modules', ['grade_level'], unique=False)
    op.create_index(op.f('ix_modules_status'), 'modules', ['status'], unique=False)
    op.create_index(op.f('ix_modules_subject'), 'modules', ['subject'], unique=False)
    op.create_table('competency_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('competency_id', sa.String(length=50), nullable=False),
    sa.Column('mastery_level', sa.Enum('NOT_STARTED', 'ATTEMPTED', 'FAMILIAR', 'PROFICIENT', 'MASTERED', name='masterylevel'), nullable=True),
    sa.Column('p_learned', sa.Float(), nullable=True),
    sa.Column('last_assessed', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_profiles_competency_id'), 'competency_profiles', ['competency_id'], unique=False)
    op.create_table('diagnostic_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('module_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='diagnosticsessionstatus'), nullable=False),
    sa.Column('recommended_group', sa.Enum('A', 'B', 'C', name='remediationgroup'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passport_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('competency_id', sa.String(length=50), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('questions_answered', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passport_assessments_competency_id'), 'passport_assessments', ['competency_id'], unique=False)
    op.create_table('pedagogical_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_type', sa.Enum('REPEATED_FAILURE', 'FRUSTRATION', 'PASSPORT_FAILED', 'INACTIVITY', 'ABANDONMENT', name='alerttriggertype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'RESOLVED', 'DISMISSED', name='alertstatus'), nullable=False),
    sa.Column('simplified_message', sa.Text(), nullable=False),
    sa.Column('expert_message', sa.Text(), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedagogical_alerts_severity'), 'pedagogical_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_pedagogical_alerts_student_id'), 'pedagogical_alerts', ['student_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('module_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('target_misconception_id', sa.String(length=50), nullable=True),
    sa.Column('estimated_time_sec', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_target_misconception_id'), 'questions', ['target_misconception_id'], unique=False)
    op.create_table('remediation_paths',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('competency_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'FAILED', 'ABANDONED', name='remediationpathstatus'), nullable=False),
    sa.Column('atoms_completed', sa.JSON(), nullable=True),
    sa.Column('current_difficulty', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_paths_competency_id'), 'remediation_paths', ['competency_id'], unique=False)
    op.create_table('alert_recipients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['pedagogical_alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atom_completions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('path_id', sa.Uuid(), nullable=False),
    sa.Column('atom_id', sa.Uuid(), nullable=False),
    sa.Column('time_spent_ms', sa.Integer(), nullable=False),
    sa.Column('interactions_count', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['atom_id'], ['knowledge_atoms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_id'], ['remediation_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnostic_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('is_correct', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('error_classification', sa.Enum('RESOURCE', 'PROCESS', 'INCIDENTAL', 'NONE', name='errorclassification'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['diagnostic_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.Enum('STUDENT', 'PARENT', 'EXPERT', name='userrole'),
               existing_nullable=False,
               postgresql_using="role::userrole")
    op.alter_column('users', 'language',
               existing_type=sa.TEXT(),
               type_=sa.Enum('AR', 'FR', name='language'),
               existing_nullable=True,
               postgresql_using="language::language")
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'language',
               existing_type=sa.Enum('AR', 'FR', name='language'),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('STUDENT', 'PARENT', 'EXPERT', name='userrole'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_table('diagnostic_answers')
    op.drop_table('atom_completions')
    op.drop_table('alert_recipients')
    op.drop_index(op.f('ix_remediation_paths_competency_id'), table_name='remediation_paths')
    op.drop_table('remediation_paths')
    op.drop_index(op.f('ix_questions_target_misconception_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_pedagogical_alerts_student_id'), table_name='pedagogical_alerts')
    op.drop_index(op.f('ix_pedagogical_alerts_severity'), table_name='pedagogical_alerts')
    op.drop_table('pedagogical_alerts')
    op.drop_index(op.f('ix_passport_assessments_competency_id'), table_name='passport_assessments')
    op.drop_table('passport_assessments')
    op.drop_table('diagnostic_sessions')
    op.drop_index(op.f('ix_competency_profiles_competency_id'), table_name='competency_profiles')
    op.drop_table('competency_profiles')
    op.drop_index(op.f('ix_modules_subject'), table_name='modules')
    op.drop_index(op.f('ix_modules_status'), table_name='modules')
    op.drop_index(op.f('ix_modules_grade_level'), table_name='modules')
    op.drop_index(op.f('ix_modules_competency_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_knowledge_atoms_competency_id'), table_name='knowledge_atoms')
    op.drop_table('knowledge_atoms')
    # ### end Alembic commands ###
